### PR TITLE
feat(boom): upgraded toolset to current charts and tool releases

### LINKED ISSUE #138: Update Ambassador
Update Ambassador to `1.4.3`

## Releas
https://github.com/datawire/ambassador/releases/tag/v1.4.3

## Discussion
- I think it is to early to use the ambassador operator

### LINKED ISSUE #139: Update Grafana
Let's keep an eye on `Grafana 7` it should not take long to release this

## Releases
https://github.com/grafana/grafana/releases/tag/v7.0.0-beta3

### LINKED ISSUE #140: Update Logging Operator
Logging Operator did quiet evolve in the last few months.

## Releases
https://github.com/banzaicloud/logging-operator/releases/tag/3.1.0

## Discussion
- Update of existing CRD might be tricky, because the CRD Version was kept

### LINKED ISSUE #141: Update Loki
## Releases
https://github.com/grafana/loki/releases/tag/v1.4.1

### LINKED ISSUE #142: Update Prometheus Operator
## Releases
https://github.com/coreos/prometheus-operator/releases/tag/v0.39.0

### LINKED ISSUE #143: Update prom node exporter
## Releases
https://github.com/prometheus/node_exporter/releases/tag/v1.0.0-rc.1

## Discussion
- we should wait for `1.0.0` release

### LINKED ISSUE #144: Update ArgoCD
## Releases
https://github.com/argoproj/argo-cd/releases/tag/v1.5.4

### LINKED ISSUE #157: Metrics Server as default
For things like `HPA` and `kubectl top` would it be great if we also deploy the metrics server by default.

Objections?

### LINKED ISSUE #161: Remove managed-by selectors from prometheus

### PR DESCRIPTION
**Pull request by stebenz**

### CODE REVIEW

**Comment by buehler** [comment]
👏

**Comment by fforootd** [comment]
@buehler we heard you 😁 next week we will merge this

**Comment by fforootd** [comment]
@stebenz we should incorporate this https://grafana.com/blog/2020/10/15/were-making-prometheus-use-less-memory-and-restart-faster

**Comment by stebenz** [comment]
> @stebenz we should incorporate this https://grafana.com/blog/2020/10/15/were-making-prometheus-use-less-memory-and-restart-faster

it's already incorporated, with the toolupgrade prometheus is on version 2.20.1

**Comment by fforootd** [comment]
@caos/orbos since this is working, we should merge this ASAP

Any objections?

**Review by fforootd — APPROVED** [review]

**Pull request merged**
