### PR TITLE
chore: always use email orbos@caos.ch

### PR DESCRIPTION
**Pull request by eliobischof**

### CODE REVIEW

**Comment by fforootd** [comment]
why don't we use something with orbos.ch?

We actually own that domain

**Comment by eliobischof** [comment]
TODO:
- [ ] Switch to an ORBOS email domain
- [ ] Pass email domain with New

**Comment by eliobischof** [comment]
> why don't we use something with orbos.ch?
> 
> We actually own that domain

@fforootd What about ops@orbos.ch and ops@zitadel.ch?

**Comment by eliobischof** [comment]
closing this as the implementation doesn't match requirements anymore

**Pull request closed without merging**
