### PR TITLE
fix: handle temporary kubeapi outages

### PR DESCRIPTION
**Pull request by eliobischof**
stop blindly joining nodes only because kubeapi was temporarily down
when querying their states

untested

### CODE REVIEW

**Review by stebenz — APPROVED** [review]

**Comment by stebenz** [comment]
merge master again for functioning pipeline for dev build

**Review by stebenz — APPROVED** [review]

**Comment by fforootd** [comment]
we should also apply limits for the node-agent or restart it on a regular basis to prevent memory problems

e.g restart it every 23h

```
[Service]
Restart=always
RuntimeMaxSec=82800
```

**Comment by eliobischof** [comment]
yes, this is already noted in #85

**Comment by fforootd** [comment]
ok, but we should do this immediately. 😁 
or what are we waiting for?

**Pull request merged**
