### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by mffap**

### CODE REVIEW

**Comment by eliobischof** [comment]
I think the placeholder is for companies using the code, not for CAOS

**Comment by mffap** [comment]
@eliobischof you're right. It's actually in "How to apply this license to your work". Sorry, then we should leave it as it is.

**Comment by fforootd** [comment]
That's what I meant on the phone :-)

Florian Forster

H e a d   o f C A O S

Phone:  +41 79 956 39 01

Web:      www.caos.ch

**Comment by mffap** [comment]
Yes - looked at Docker Repo, they put their name in. Now I checked a couple more. 
Apparently found with high precision a wrong example :)

**Pull request closed without merging**
